const data={
    products:[
        {
            _id:'1',
            name: 'Slim-fit shirt',
            category:'shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },

        {
            _id:'2',
            name: 'Slim-fit shirt',
            category:'shirts',
            image:'/images/p2.jpg',
            price: 1200,
            brand:'Nike',
            rating:4.6,
            numReviews:100,
            description:'high quality product',
        },
        {
            _id:'3',
            name: 'Slim-fit shirt',
            category:'shirts',
            image:'/images/p3.jpg',
            price: 1220,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name: 'Slim-fit pants',
            category:'pants',
            image:'/images/p4.jpg',
            price: 1200,
            brand:'Nike',
            rating:4.5,
            numReviews:100,
            description:'high quality product',
        },
        {
            _id:'5',
            name: 'Slim-fir pants',
            category:'pants',
            image:'/images/p5.jpg',
            price: 120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name: 'Slim-fir pant',
            category:'pants',
            image:'/images/p6.jpg',
            price: 800,
            brand:'Nike',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },

    ],
}

export default data;